### ISSUE TITLE
Include link to walkthrough video

### ISSUE THREAD

**Issue by JoshOrndorff** [proof-media/rchain-grpc#13]
* rchain-grpc version: 0.0.11
* Python version: 3.7
* Operating System: All

### Description
On 22 October, @pdonorio gave us a tour of how to use this module. @jimscarver can you please post the video link here, so we can get it into their documentation?

**Comment by jimscarver** [comment]
Thanks @pdonorio for great tour of the awesome work you have done. 

The video from the tour is at https://youtu.be/H_pmVff7c3Q

[slides](https://nbviewer.jupyter.org/format/slides/github/proof-media/rchain-notebook/blob/master/notebooks/walk-through.ipynb#/)

Both are great resources.

**Comment by jimscarver** [comment]
https://youtu.be/H_pmVff7c3Q

[slides](https://nbviewer.jupyter.org/format/slides/github/proof-media/rchain-notebook/blob/master/notebooks/walk-through.ipynb#/)

**Comment by pdonorio** [comment]
Thanks! :D
Updated: https://proof-media.github.io/rchain-grpc
