### ISSUE TITLE
Support multiple python versions

### ISSUE THREAD

**Issue by pdonorio** [proof-media/rchain-grpc#5]
Currently tested on 3.7. 
- [x] 3.6 should be added with not many difficulties
- [x] verify if older versions are needed
- [x] find the better ways to test it also all locally (with Docker)

**Comment by pdonorio** [comment]
Find also the better way to test it also all locally with Docker.

**Comment by pdonorio** [comment]
Python 3.6 brings infinite recursions, e.g. `RecursionError: maximum recursion depth exceeded.`. 

Edit: also see [this comment](https://github.com/proof-media/rchain-grpc/issues/18#issuecomment-433890529) for more info.

**Comment by beetleman** [comment]
python 3.6 support #19

**Comment by pdonorio** [comment]
> find the better ways to test it also all locally (with Docker)

added a simple [script](https://github.com/proof-media/rchain-grpc/blob/master/test_all_python_versions.sh)

**Comment by pdonorio** [comment]
For the moment no support is requested below python `3.6`
