### ISSUE TITLE
Move to official rchain repo

### ISSUE THREAD

**Issue by pdonorio** [proof-media/rchain-grpc#8]
This issue depends on #4

**Comment by pdonorio** [comment]
Questions:

- What name should the new repo have?
- Should the repo be a fork of this one?
- Who's handling the other accounts (e.g. travis, pyup, readthedocs, etc.)?
- What duties are requested to fullfil?

**Comment by pdonorio** [comment]
> What name should the new repo have?

Following the Ethereum example https://github.com/ethereum/web3.py, we might consider a similar approach:
- rchain/rchain-api.py
- rchain/rchain.py
- rchain/api.py
- rchain/web3.py
etc.

Also currently the main name has been already taken by the JS library :)
https://github.com/rchain/rchain-api

**Comment by beetleman** [comment]
adding `.py` suffix is not common practice in python world so I vote for `rchain-api-python`

**Comment by dckc** [comment]
at @pdonorio 's request, I created a repo in https://github.com/rchain-community/ . I called it https://github.com/rchain-community/rchain-grpc/ . @pdonorio should be able to push to it, if not add new collaborators.

If you want to preserve issues, watchers, and stars, we'd have to move this repo. That's a little more work but I've done it a couple times lately.

If this suffices, please close this issue. Otherwise, let me know what more you want / need.

**Comment by pdonorio** [comment]
Thank you @dckc!

I was wondering today if there was a way in middle e.g. you forking this repo into rchain-community and giving me and `beetleman` permissions. 

If that wouldn't work for any reason we can just copy the code there also, not a big issue.

**Comment by dckc** [comment]
You want rchain-community to be downstream of proof-media rather than the other way around?

**Comment by pdonorio** [comment]
If we fork we keep the commits, 
then we just block this repo and mark it as deprecated linking the new one in rchain-community.

**Comment by dckc** [comment]
The commits are part of the git history. You keep that no matter what. The question is the github fork structure, PRs, issues, stars, and watchers.

**Comment by dckc** [comment]
A git push will keep all the commits.

**Comment by pdonorio** [comment]
Great, I've pushed and it's fine:
https://github.com/rchain-community/rchain-grpc
Issues, PRs, stars and forks don't matter much up to now.

I just have to setup travis, pypi upload and pyup in the new repo (hope to take a shot tomorrow) and then let the rchain community know on discord.

Thanks a lot, let's close here.
